export const USERNAME_CHANGE = "USERNAME_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const USER_ATTEMPT = "USER_ATTEMPT";
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL"